<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BankSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $banks = [
            [
                'bank_name' => 'BANK1',
                'gl_no' => '10201 RHB BANK 9951',
                'initial_amount' => 0,
                'currency' => 'CAD',
                'revenue_default' => false,
                'cost_default' => false,
                'notes_receivable' => null,
                'notes_payable' => null,
                'is_active' => false,
                'inactive_date' => '2025-07-22',
                'check_by_sequence' => false,
                'clear_check_by_cycle' => false,
                'display_remark' => false,
                'invoice_remark' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bank_name' => 'Bank2',
                'gl_no' => '10210 CASH IN BANK: CHECKING 5517',
                'initial_amount' => 0,
                'currency' => 'CAD',
                'revenue_default' => false,
                'cost_default' => false,
                'notes_receivable' => null,
                'notes_payable' => null,
                'is_active' => false,
                'inactive_date' => '2025-07-22',
                'check_by_sequence' => false,
                'clear_check_by_cycle' => false,
                'display_remark' => false,
                'invoice_remark' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bank_name' => 'Bank3',
                'gl_no' => '10210 CASH IN BANK: ANAC 5517',
                'initial_amount' => 0,
                'currency' => 'CAD',
                'revenue_default' => false,
                'cost_default' => false,
                'notes_receivable' => null,
                'notes_payable' => null,
                'is_active' => false,
                'inactive_date' => '2025-07-22',
                'check_by_sequence' => false,
                'clear_check_by_cycle' => false,
                'display_remark' => false,
                'invoice_remark' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bank_name' => 'Bank4',
                'gl_no' => '10960 PETTY CASH',
                'initial_amount' => 0,
                'currency' => 'CAD',
                'revenue_default' => false,
                'cost_default' => false,
                'notes_receivable' => null,
                'notes_payable' => null,
                'is_active' => false,
                'inactive_date' => '2025-07-22',
                'check_by_sequence' => false,
                'clear_check_by_cycle' => false,
                'display_remark' => false,
                'invoice_remark' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bank_name' => 'Bank5',
                'gl_no' => '10601 RHB BANK 9951',
                'initial_amount' => 0,
                'currency' => 'CAD',
                'revenue_default' => false,
                'cost_default' => false,
                'notes_receivable' => null,
                'notes_payable' => null,
                'is_active' => false,
                'inactive_date' => '2025-07-22',
                'check_by_sequence' => false,
                'clear_check_by_cycle' => false,
                'display_remark' => false,
                'invoice_remark' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bank_name' => 'Bank6',
                'gl_no' => '20110 CHASE CREDIT CARD 7034',
                'initial_amount' => 0,
                'currency' => 'CAD',
                'revenue_default' => false,
                'cost_default' => false,
                'notes_receivable' => null,
                'notes_payable' => null,
                'is_active' => false,
                'inactive_date' => '2025-07-22',
                'check_by_sequence' => false,
                'clear_check_by_cycle' => false,
                'display_remark' => false,
                'invoice_remark' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bank_name' => 'Bank7',
                'gl_no' => '20110 CHASE CREDIT CARD 7634',
                'initial_amount' => 0,
                'currency' => 'CAD',
                'revenue_default' => false,
                'cost_default' => false,
                'notes_receivable' => null,
                'notes_payable' => null,
                'is_active' => false,
                'inactive_date' => '2025-07-22',
                'check_by_sequence' => false,
                'clear_check_by_cycle' => false,
                'display_remark' => false,
                'invoice_remark' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bank_name' => 'Bank8',
                'gl_no' => '10610 PETTY CASH',
                'initial_amount' => 0,
                'currency' => 'CAD',
                'revenue_default' => false,
                'cost_default' => false,
                'notes_receivable' => null,
                'notes_payable' => null,
                'is_active' => false,
                'inactive_date' => '2025-07-22',
                'check_by_sequence' => false,
                'clear_check_by_cycle' => false,
                'display_remark' => false,
                'invoice_remark' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bank_name' => 'Bank9',
                'gl_no' => '10820 RHB PASS BALANCE',
                'initial_amount' => 0,
                'currency' => 'CAD',
                'revenue_default' => false,
                'cost_default' => false,
                'notes_receivable' => null,
                'notes_payable' => null,
                'is_active' => false,
                'inactive_date' => '2025-07-22',
                'check_by_sequence' => false,
                'clear_check_by_cycle' => false,
                'display_remark' => false,
                'invoice_remark' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bank_name' => 'Bank10',
                'gl_no' => '20140 CHASE CREDIT CARD 9934',
                'initial_amount' => 0,
                'currency' => 'CAD',
                'revenue_default' => false,
                'cost_default' => false,
                'notes_receivable' => null,
                'notes_payable' => null,
                'is_active' => false,
                'inactive_date' => '2025-07-22',
                'check_by_sequence' => false,
                'clear_check_by_cycle' => false,
                'display_remark' => false,
                'invoice_remark' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($banks as $bank) {
            DB::table('banks')->insert($bank);
        }
    }
}
