<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CurrencyRateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $rates = [
            [
                'from_currency' => 'CAD',
                'to_currency' => 'USD',
                'as_of_date' => '2019-06-30',
                'rate_internal' => 1,
                'rate_external' => 0.77,
                'created_by' => 'Get/Freight (Random)',
                'created_at' => '2019-06-30 10:30:10',
                'modified_by' => 'Matthew Dany (user:08)',
                'updated_at' => '2023-01-22',
                'remark' => null,
            ],
            [
                'from_currency' => 'CAD',
                'to_currency' => 'USD',
                'as_of_date' => '2019-06-27',
                'rate_internal' => 1,
                'rate_external' => 0.77,
                'created_by' => 'Get/Freight (Random)',
                'created_at' => '2019-06-30',
                'modified_by' => 'Demo_001 [Demo_001]',
                'updated_at' => '2019-06-22',
                'remark' => null,
            ],
            [
                'from_currency' => 'CAD',
                'to_currency' => 'USD',
                'as_of_date' => '2019-03-13',
                'rate_internal' => 1,
                'rate_external' => 0.77,
                'created_by' => 'Get/Freight (Random)',
                'created_at' => '2019-05-30',
                'modified_by' => 'Demo_001 [Demo_001]',
                'updated_at' => '2019-06-22',
                'remark' => null,
            ],
            [
                'from_currency' => 'CAD',
                'to_currency' => 'USD',
                'as_of_date' => '2021-06-30',
                'rate_internal' => 1,
                'rate_external' => 0.77,
                'created_by' => 'Get/Freight (Random)',
                'created_at' => '2019-05-30',
                'modified_by' => 'Demo_JKT [Demo_JKT]',
                'updated_at' => '2019-08-31',
                'remark' => null,
            ],
            [
                'from_currency' => 'CAD',
                'to_currency' => 'USD',
                'as_of_date' => '2023-08-31',
                'rate_internal' => 0.83,
                'rate_external' => 0.83,
                'created_by' => 'Get/Freight (Random)',
                'created_at' => '2026-12-22',
                'modified_by' => 'Get/Freight (Random)',
                'updated_at' => '2021-08-05',
                'remark' => null,
            ],
            [
                'from_currency' => 'CAD',
                'to_currency' => 'USD',
                'as_of_date' => '2021-08-01',
                'rate_internal' => 0.79,
                'rate_external' => 0.79,
                'created_by' => 'Get/Freight (Random)',
                'created_at' => '2021-09-21',
                'modified_by' => 'Get/Freight (Random)',
                'updated_at' => '2021-05-21',
                'remark' => null,
            ],
            [
                'from_currency' => 'CAD',
                'to_currency' => 'USD',
                'as_of_date' => '2021-10-06',
                'rate_internal' => 1,
                'rate_external' => 0.83,
                'created_by' => 'DEMO_179 [DEMO_179]',
                'created_at' => '2021-10-06',
                'modified_by' => 'DEMO_179 [DEMO_179]',
                'updated_at' => '2021-10-06',
                'remark' => null,
            ],
            [
                'from_currency' => 'CAD',
                'to_currency' => 'USD',
                'as_of_date' => '2021-10-27',
                'rate_internal' => 1.26,
                'rate_external' => 0.83,
                'created_by' => 'Get/Freight (Random)',
                'created_at' => '2021-10-27',
                'modified_by' => 'DEMO_179 [DEMO_179]',
                'updated_at' => '2021-10-27',
                'remark' => null,
            ],
            [
                'from_currency' => 'CAD',
                'to_currency' => 'USD',
                'as_of_date' => '2021-11-08',
                'rate_internal' => 1.23,
                'rate_external' => 0.805,
                'created_by' => 'DEMO_179 [DEMO_179]',
                'created_at' => '2021-11-02',
                'modified_by' => 'DEMO_179 [DEMO_179]',
                'updated_at' => '2021-11-02',
                'remark' => null,
            ],
            [
                'from_currency' => 'CAD',
                'to_currency' => 'USD',
                'as_of_date' => '2022-08-11',
                'rate_internal' => 1.29,
                'rate_external' => 0.79,
                'created_by' => 'Manager Adriana',
                'created_at' => '2022-01-24',
                'modified_by' => 'Get/Freight (Random)',
                'updated_at' => '2023-01-11',
                'remark' => null,
            ],
            [
                'from_currency' => 'CAD',
                'to_currency' => 'USD',
                'as_of_date' => '2023-02-23',
                'rate_internal' => 0.74,
                'rate_external' => 0.74,
                'created_by' => 'Demo_JKT [Demo_JKT]',
                'created_at' => '2023-02-09',
                'modified_by' => 'Get/Freight (Random)',
                'updated_at' => '2024-08-08',
                'remark' => null,
            ],
            [
                'from_currency' => 'CAD',
                'to_currency' => 'USD',
                'as_of_date' => '2024-08-01',
                'rate_internal' => 0.74,
                'rate_external' => 0.74,
                'created_by' => 'Demo_JKT [Demo_JKT]',
                'created_at' => '2024-12-12',
                'modified_by' => 'Get/Freight (Random)',
                'updated_at' => '2024-12-12',
                'remark' => null,
            ],
            [
                'from_currency' => 'CAD',
                'to_currency' => 'USD',
                'as_of_date' => '2024-08-11',
                'rate_internal' => 0.74,
                'rate_external' => 0.74,
                'created_by' => 'Get/Freight (Random)',
                'created_at' => '2024-08-26',
                'modified_by' => 'Get/Freight (Random)',
                'updated_at' => '2024-08-26',
                'remark' => null,
            ],
            [
                'from_currency' => 'CAD',
                'to_currency' => 'USD',
                'as_of_date' => '2025-12-31',
                'rate_internal' => 0.000038,
                'rate_external' => 0.000038,
                'created_by' => 'Get/Freight (Random)',
                'created_at' => '2026-03-13',
                'modified_by' => 'Get/Freight (Random)',
                'updated_at' => '2026-03-12',
                'remark' => null,
            ],
            [
                'from_currency' => 'CAD',
                'to_currency' => 'USD',
                'as_of_date' => '2026-07-06',
                'rate_internal' => 1,
                'rate_external' => 0.825,
                'created_by' => 'Get/Freight (Random)',
                'created_at' => '2026-07-07',
                'modified_by' => 'Get/Freight (Random)',
                'updated_at' => '2026-07-07',
                'remark' => null,
            ],
            [
                'from_currency' => 'CAD',
                'to_currency' => 'USD',
                'as_of_date' => '2026-07-09',
                'rate_internal' => 0.72,
                'rate_external' => 0.72,
                'created_by' => 'Get/Freight (Random)',
                'created_at' => '2026-07-10',
                'modified_by' => 'Get/Freight (Random)',
                'updated_at' => '2026-07-10',
                'remark' => null,
            ],
            [
                'from_currency' => 'CAD',
                'to_currency' => 'USD',
                'as_of_date' => '2026-07-09',
                'rate_internal' => 0.72,
                'rate_external' => 0.72,
                'created_by' => 'Get/Freight (Random)',
                'created_at' => '2026-07-09',
                'modified_by' => 'Get/Freight (Random)',
                'updated_at' => '2026-07-09',
                'remark' => 'Generated by Accounting Blink',
            ],
        ];

        foreach ($rates as $rate) {
            DB::table('currency_rates')->insert($rate);
        }
    }
}
